/*
 * MtnMOMCollectionLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mtn.momodeveloper.sandbox;

import java.util.HashMap;
import java.util.Map;

import com.mtn.momodeveloper.sandbox.models.*;

public class Configuration {
    //TODO: Replace the ocpApimSubscriptionKey with an appropriate value
    public static String ocpApimSubscriptionKey = "";

    /**
     * Current API environment
     */
    public static Environments environment = Environments.PRODUCTION;

    /**
     * Get base URI by current environment
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public static String getBaseUri(Servers server) {
        StringBuilder baseUrl = new StringBuilder(environmentMapper(Configuration.environment, server));
        Map<String, Object> parameters = new HashMap<String, Object>();
        APIHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }
    
    /**
     * Get base URI by current environment
     * @return Processed base URI
     */
    public static String getBaseUri() {
        return Configuration.getBaseUri(Servers.ENUM_DEFAULT);
    }
    
    /**
     * Base URLs by environments and server aliases 
     */

    private static String environmentMapper(Environments environments, Servers servers) {
		String url = "";
		if(environments.equals(Environments.PRODUCTION)) {
			if(servers.equals(Servers.ENUM_DEFAULT))
				url = "https://sandbox.momodeveloper.mtn.com/collection";
			if(servers.equals(Servers.LIVE))
				url = "https://live.momodeveloper.mtn.com/collection";
		}
		return url;
	}
}
