/*
 * MtnMOMCollectionLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mtn.momodeveloper.sandbox;

import com.mtn.momodeveloper.sandbox.controllers.*;
import com.mtn.momodeveloper.sandbox.http.client.HttpClient;

public class MtnMOMCollectionClient {
    /**
     * Singleton access to Client controller
     * @return	Returns the APIController instance 
     */
    public APIController getClient() {
        return APIController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public MtnMOMCollectionClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public MtnMOMCollectionClient(String ocpApimSubscriptionKey) {
        this();
        Configuration.ocpApimSubscriptionKey = ocpApimSubscriptionKey;
    }
}