/*
 * MtnMOMCollectionLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mtn.momodeveloper.sandbox.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class BooleanResult 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 92642741013633971L;
    private Boolean result;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("result")
    public Boolean getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("result")
    public void setResult (Boolean value) { 
        this.result = value;
        notifyObservers(this.result);
    }
 
}
