/*
 * MtnMOMCollectionLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mtn.momodeveloper.sandbox.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum CodeEnum {
    PAYEE_NOT_FOUND, //TODO: Write general description for this element
    PAYER_NOT_FOUND, //TODO: Write general description for this element
    NOT_ALLOWED, //TODO: Write general description for this element
    NOT_ALLOWED_TARGET_ENVIRONMENT, //TODO: Write general description for this element
    INVALID_CALLBACK_URL_HOST, //TODO: Write general description for this element
    INVALID_CURRENCY, //TODO: Write general description for this element
    SERVICE_UNAVAILABLE, //TODO: Write general description for this element
    INTERNAL_PROCESSING_ERROR, //TODO: Write general description for this element
    NOT_ENOUGH_FUNDS, //TODO: Write general description for this element
    PAYER_LIMIT_REACHED, //TODO: Write general description for this element
    PAYEE_NOT_ALLOWED_TO_RECEIVE, //TODO: Write general description for this element
    PAYMENT_NOT_APPROVED, //TODO: Write general description for this element
    RESOURCE_NOT_FOUND, //TODO: Write general description for this element
    APPROVAL_REJECTED, //TODO: Write general description for this element
    EXPIRED, //TODO: Write general description for this element
    TRANSACTION_CANCELED, //TODO: Write general description for this element
    RESOURCE_ALREADY_EXIST; //TODO: Write general description for this element

    private static TreeMap<String, CodeEnum> valueMap = new TreeMap<String, CodeEnum>();
    private String value;

    static {
        PAYEE_NOT_FOUND.value = "PAYEE_NOT_FOUND";
        PAYER_NOT_FOUND.value = "PAYER_NOT_FOUND";
        NOT_ALLOWED.value = "NOT_ALLOWED";
        NOT_ALLOWED_TARGET_ENVIRONMENT.value = "NOT_ALLOWED_TARGET_ENVIRONMENT";
        INVALID_CALLBACK_URL_HOST.value = "INVALID_CALLBACK_URL_HOST";
        INVALID_CURRENCY.value = "INVALID_CURRENCY";
        SERVICE_UNAVAILABLE.value = "SERVICE_UNAVAILABLE";
        INTERNAL_PROCESSING_ERROR.value = "INTERNAL_PROCESSING_ERROR";
        NOT_ENOUGH_FUNDS.value = "NOT_ENOUGH_FUNDS";
        PAYER_LIMIT_REACHED.value = "PAYER_LIMIT_REACHED";
        PAYEE_NOT_ALLOWED_TO_RECEIVE.value = "PAYEE_NOT_ALLOWED_TO_RECEIVE";
        PAYMENT_NOT_APPROVED.value = "PAYMENT_NOT_APPROVED";
        RESOURCE_NOT_FOUND.value = "RESOURCE_NOT_FOUND";
        APPROVAL_REJECTED.value = "APPROVAL_REJECTED";
        EXPIRED.value = "EXPIRED";
        TRANSACTION_CANCELED.value = "TRANSACTION_CANCELED";
        RESOURCE_ALREADY_EXIST.value = "RESOURCE_ALREADY_EXIST";

        valueMap.put("PAYEE_NOT_FOUND", PAYEE_NOT_FOUND);
        valueMap.put("PAYER_NOT_FOUND", PAYER_NOT_FOUND);
        valueMap.put("NOT_ALLOWED", NOT_ALLOWED);
        valueMap.put("NOT_ALLOWED_TARGET_ENVIRONMENT", NOT_ALLOWED_TARGET_ENVIRONMENT);
        valueMap.put("INVALID_CALLBACK_URL_HOST", INVALID_CALLBACK_URL_HOST);
        valueMap.put("INVALID_CURRENCY", INVALID_CURRENCY);
        valueMap.put("SERVICE_UNAVAILABLE", SERVICE_UNAVAILABLE);
        valueMap.put("INTERNAL_PROCESSING_ERROR", INTERNAL_PROCESSING_ERROR);
        valueMap.put("NOT_ENOUGH_FUNDS", NOT_ENOUGH_FUNDS);
        valueMap.put("PAYER_LIMIT_REACHED", PAYER_LIMIT_REACHED);
        valueMap.put("PAYEE_NOT_ALLOWED_TO_RECEIVE", PAYEE_NOT_ALLOWED_TO_RECEIVE);
        valueMap.put("PAYMENT_NOT_APPROVED", PAYMENT_NOT_APPROVED);
        valueMap.put("RESOURCE_NOT_FOUND", RESOURCE_NOT_FOUND);
        valueMap.put("APPROVAL_REJECTED", APPROVAL_REJECTED);
        valueMap.put("EXPIRED", EXPIRED);
        valueMap.put("TRANSACTION_CANCELED", TRANSACTION_CANCELED);
        valueMap.put("RESOURCE_ALREADY_EXIST", RESOURCE_ALREADY_EXIST);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static CodeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CodeEnum values to list of string values
     * @param toConvert The list of CodeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<CodeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (CodeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 