/*
 * MtnMOMCollectionLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mtn.momodeveloper.sandbox.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum PartyIdTypeEnum {
    MSISDN, //TODO: Write general description for this element
    EMAIL, //TODO: Write general description for this element
    PARTY_CODE; //TODO: Write general description for this element

    private static TreeMap<String, PartyIdTypeEnum> valueMap = new TreeMap<String, PartyIdTypeEnum>();
    private String value;

    static {
        MSISDN.value = "MSISDN";
        EMAIL.value = "EMAIL";
        PARTY_CODE.value = "PARTY_CODE";

        valueMap.put("MSISDN", MSISDN);
        valueMap.put("EMAIL", EMAIL);
        valueMap.put("PARTY_CODE", PARTY_CODE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static PartyIdTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PartyIdTypeEnum values to list of string values
     * @param toConvert The list of PartyIdTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<PartyIdTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (PartyIdTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 