/*
 * MtnMOMCollectionLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mtn.momodeveloper.sandbox.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Party 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -4195354572524295927L;
    private PartyIdTypeEnum partyIdType;
    private String partyId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("partyIdType")
    public PartyIdTypeEnum getPartyIdType ( ) { 
        return this.partyIdType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("partyIdType")
    public void setPartyIdType (PartyIdTypeEnum value) { 
        this.partyIdType = value;
        notifyObservers(this.partyIdType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("partyId")
    public String getPartyId ( ) { 
        return this.partyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("partyId")
    public void setPartyId (String value) { 
        this.partyId = value;
        notifyObservers(this.partyId);
    }
 
}
