/*
 * MtnMOMCollectionLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mtn.momodeveloper.sandbox.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.mtn.momodeveloper.sandbox.http.client.HttpContext;

public class TokenPost401ApplicationJsonResponseException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = 79794706313023141L;
    private String error;
    /** GETTER
     * An error code.
     */
    @JsonGetter("error")
    public String getMError ( ) { 
        return this.error;
    }
    
    /** SETTER
     * An error code.
     */
    @JsonSetter("error")
    private void setMError (String value) { 
        this.error = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public TokenPost401ApplicationJsonResponseException(String reason, HttpContext context) {
        super(reason, context);
    }
}
